services:
  postgres:
    container_name: fundingrate-postgres
    image: postgres:17
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: fundingrate-redis
    image: redis:8
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

  rabbitmq:
    container_name: fundingrate-rabbitmq
    image: rabbitmq:4
    ports:
      - 5672:5672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  prometheus:
    container_name: fundingrate-prometheus
    image: prom/prometheus:v3.5.0
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus

  grafana:
    container_name: fundingrate-grafana
    image: grafana/grafana:12.1.0
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana

  loki:
    container_name: fundingrate-loki
    image: grafana/loki:3.5.3
    ports:
      - 3100:3100
    volumes:
      - loki_data:/loki

  jaeger:
    container_name: fundingrate-jaeger
    image: jaegertracing/all-in-one:1.71.0
    ports:
      - 6006:6006
      - 16686:16686
      - 14268:14268

volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  prometheus_data:
  grafana_data:
  loki_data:
