site_name: connector
repo_url: https://github.com/AutomaticTrading/connector
site_url: https://AutomaticTrading.github.io/connector
site_description: 📡 Python client for seamless integration with crypto exchanges.
site_author: andreyfesunov
edit_uri: edit/main/docs/
repo_name: AutomaticTrading/connector
copyright: Maintained by <a href="https://AutomaticTrading.com">AutomaticTrading</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/connector"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AutomaticTrading/connector
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/connector

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
